/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.casemodule;

import java.util.List;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author root
 */
public class AddImageWizardConfigureEncryptionVisual extends JPanel {

    static final Logger logger = Logger.getLogger(AddImageWizardConfigureEncryptionVisual.class.getName());
    List<DecryptionProvider> providerList;
    private final AddImageWizardConfigureEncryptionPanel encryptionPanel;

    public AddImageWizardConfigureEncryptionVisual(AddImageWizardConfigureEncryptionPanel encryptionPanel) {
        this.encryptionPanel = encryptionPanel;
        initComponents();
    }

    private void SetPanels() {
        this.removeAll();
        this.setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));

        for (DecryptionProvider decryptionProvider : providerList) {
            this.add(decryptionProvider.getPanel());
        }
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void updateProviderList(List<DecryptionProvider> cr) {
        providerList = cr;
        SetPanels();
    }

}
