/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.sleuthkit.autopsy.casemodule;

import java.awt.BorderLayout;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author root
 */
public class AddImageWizardConfigureEncryptionVisual extends JPanel {

	static final Logger logger = Logger.getLogger(AddImageWizardConfigureEncryptionVisual.class.getName());
	List<DecryptionProvider> providerList;
	private final AddImageWizardConfigureEncryptionPanel encryptionPanel;

	public AddImageWizardConfigureEncryptionVisual(AddImageWizardConfigureEncryptionPanel encryptionPanel) {
		this.encryptionPanel = encryptionPanel;
		initComponents();
		typePanel.setLayout(new BorderLayout());
	}

	private void SetPanels() {
		typePanel.removeAll();
		providerList.stream().forEach((x) -> {
			typePanel.add(x.getPanel(), BorderLayout.CENTER);
		});
		typePanel.validate();
		typePanel.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                typePanel = new javax.swing.JPanel();

                javax.swing.GroupLayout typePanelLayout = new javax.swing.GroupLayout(typePanel);
                typePanel.setLayout(typePanelLayout);
                typePanelLayout.setHorizontalGroup(
                        typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 502, Short.MAX_VALUE)
                );
                typePanelLayout.setVerticalGroup(
                        typePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 220, Short.MAX_VALUE)
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(194, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(typePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(63, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel typePanel;
        // End of variables declaration//GEN-END:variables

	void updateProviderList(List<DecryptionProvider> cr) {
		providerList = cr;
		SetPanels();
	}

}
